### ISSUE TITLE
测试代码报错

### ISSUE THREAD

**Issue by chunyuxiaodao** [Linzy0227/SRMNet#2]
感谢作者的杰出工作。目前我已完成训练，但在测试时会报RuntimeError: output with shape [1, 1, 128, 128, 128] doesn't match the broadcast shape [1, 128, 128, 128, 128]这个错，具体是在predict.py中的121行weight1[:, :, h:h+patch_size, w:w+patch_size, z:z+patch_size] += one_tensor 
请问作者是否会遇到这个问题，出现这个报错可能的原因是什么？应该如何解决？十分希望能得到您的指导和帮助！

![微信图片_20240529165614](https://github.com/Linzy0227/SRMNet/assets/85382887/7c510cb9-047d-497a-a2fc-3113457ae8ad)

**Comment by Linzy0227** [comment]
从报错的情况来看，应该是shape不匹配，不知道你是否修改了测试代码或者数据是否处理正确。

**Comment by nnnnnnml** [comment]
> 感谢作者的杰出工作。目前我已完成训练，但在测试时会报RuntimeError: output with shape [1, 1, 128, 128, 128] doesn't match the broadcast shape [1, 128, 128, 128, 128]这个错，具体是在predict.py中的121行weight1[:, :, h:h+patch_size, w:w+patch_size, z:z+patch_size] += one_tensor 请问作者是否会遇到这个问题，出现这个报错可能的原因是什么？应该如何解决？十分希望能得到您的指导和帮助！
> 
> ![微信图片_20240529165614](https://private-user-images.githubusercontent.com/85382887/334730986-7c510cb9-047d-497a-a2fc-3113457ae8ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTMzNjIsIm5iZiI6MTcxODUxMzA2MiwicGF0aCI6Ii84NTM4Mjg4Ny8zMzQ3MzA5ODYtN2M1MTBjYjktMDQ3ZC00OTdhLWEyZmMtMzExMzQ1N2FlOGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA0NDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YWI5ZDcwZGQ0ZjcwMTZiZTVlNjA0NTE3YzJkMmNiNzZmY2I1YjFmYmIyYTBmMzQ0OGMxZDM5M2U2NjM5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.caGEC1s2CQ1_TvmPThmlhk5WscNJrUab_4IHxo1LTpI)

我也是这个问题，想问一下你解决了吗

**Comment by nnnnnnml** [comment]
> 从报错的情况来看，应该是shape不匹配，不知道你是否修改了测试代码或者数据是否处理正确。

没有修改代码，不知道是不是数据集的问题，数据集我从kaggle网站上下的

**Comment by Linzy0227** [comment]
> > 从报错的情况来看，应该是shape不匹配，不知道你是否修改了测试代码或者数据是否处理正确。
> 
> 没有修改代码，不知道是不是数据集的问题，数据集我从kaggle网站上下的

用代码里的预处理文件处理一下
