### ISSUE TITLE
用了作者训练好的模型测试，也是这个问题，预处理按照作者的代码处理，想问问是什么原因？

### ISSUE THREAD

**Issue by nnnnnnml** [Linzy0227/SRMNet#4]
###########test postprocess###########
t2
Traceback (most recent call last):
  File "/root/autodl-tmp/SRMNet-main/test.py", line 58, in <module>
    dice_score = test_softmax(
  File "/root/autodl-tmp/SRMNet-main/predict.py", line 121, in test_softmax
    weight1[:, :, h:h+patch_size, w:w+patch_size, z:z+patch_size] += one_tensor
RuntimeError: output with shape [1, 1, 128, 128, 1] doesn't match the broadcast shape [1, 1, 128, 128, 128]

**Comment by Linzy0227** [comment]
你好，打印一下处理的数据的shape，看看有没有异常的数据。

**Comment by nnnnnnml** [comment]
你好，能分享一下训练日志吗

**Comment by nnnnnnml** [comment]
是的，有一个数据显示异常，我数据集是在kaggle网站下下载的

**Comment by nnnnnnml** [comment]
> 你好，打印一下处理的数据的shape，看看有没有异常的数据。

你好，可以分享以下2020数据集吗

**Comment by Linzy0227** [comment]
> > 你好，打印一下处理的数据的shape，看看有没有异常的数据。
> 
> 你好，可以分享以下2020数据集吗

处理后的数据太大了，没法分享，你可以单独修改一下裁剪的代码来处理一下那一个异常的数据。
