### ISSUE TITLE
你好作者，想问一下验证结果是否是使用训练测试集划分中的test.txt,我看论文中使用的是验证数据集，另外三重验证代码里有体现吗，能否提供一下呢

### ISSUE THREAD

**Issue by nnnnnnml** [Linzy0227/SRMNet#6]

**Comment by Linzy0227** [comment]
验证集其实是没用到的，这和其他对比方法都是一致的，使用训练结果最后一个epoch的权重文件测试。交叉验证只在brats2018上使用，具体的划分细节可以从RFNet这篇论文里找到。

**Comment by nnnnnnml** [comment]
好的，感谢作者的解答

**Comment by chunyuxiaodao** [comment]
你好，想请教一下test得到的数值是？ 如何最终得到ET、WT、TC下的DSC数值呢？十分需要您的解答
