### ISSUE TITLE
测试求助

### ISSUE THREAD

**Issue by chunyuxiaodao** [Linzy0227/SRMNet#8]
作者你好，向你请教， 在测试代码中得到的'whole', 'core', 'enhancing', 数值是对应论文中的‘WT’，‘TC ’，‘ET’吗？  那'enhancing_postpro'的含义是什么呢？此外我并未在找到HD95的测试代码 ，HD95应该如何计算呢？希望能得到你的指点。

**Comment by Linzy0227** [comment]
（1）'whole', 'core', 'enhancing' 分别代表whole tumor, tumor core and enhancing tumor。
（2）enhancing_postpro为后处理后的结果。
（3）HD95的代码可以从ACN这篇论文的开源代码中找到，你可以先进行测试，然后将测试的结果保存起来，最后和标签计算HD95的值。
希望能帮到你！

**Comment by chunyuxiaodao** [comment]
好的十分感谢您的解答，我利用您提供的pth文件进行了两次测试，‘WT’，‘TC ’能复现出来论文里的数值，但‘ET’仅能得到0.58几 ，与您的平均0.62还有较大差距，十分困惑为什么会这样。
![image](https://github.com/user-attachments/assets/a86dc5c7-27bd-4899-88cb-176931bdfa49)

**Comment by chunyuxiaodao** [comment]
谢谢你的解答

**Comment by Linzy0227** [comment]
> 好的十分感谢您的解答，我利用您提供的pth文件进行了两次测试，‘WT’，‘TC ’能复现出来论文里的数值，但‘ET’仅能得到0.58几 ，与您的平均0.62还有较大差距，十分困惑为什么会这样。 ![image](https://private-user-images.githubusercontent.com/85382887/360512380-a86dc5c7-27bd-4899-88cb-176931bdfa49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Njg1NTIsIm5iZiI6MTcyNDQ2ODI1MiwicGF0aCI6Ii84NTM4Mjg4Ny8zNjA1MTIzODAtYTg2ZGM1YzctMjdiZC00ODk5LTg4Y2ItMTc2OTMxYmRmYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDAyNTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTQ1ZjljYzc4ZjJlZTIxZDlkYjlkMzAxYTNkZWRjMzk1ZDYyYmQ1OGIxNzdkODI0YzZkZjQ4YzA4ZmNhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3U5oeuqc5MYz6B3-FsmKWhs_OkuHWS4QRngw6CJ3hks)

用了后处理的指标，具体参考rfnet论文里的介绍

**Comment by chunyuxiaodao** [comment]
十分感谢你耐心的解答，所以我可以理解为论文‘ET’的值 应该是测试代码中'enhancing_postpro'的测试的平均值 是吗 真的非常感谢您
